# -*- coding: utf-8 -*-
"""BDMI_Final_Project_Financial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/120PAVCUC5wdbRoWDaoRLJe_JvYFLLor1

#BDMI Final Project - Financial - Elias Jr
"""

# Commented out IPython magic to ensure Python compatibility.
# Clone the official repository
!git clone https://github.com/hiyouga/LLaMA-Factory.git
# %cd LLaMA-Factory

# Install the package along with training metrics dependencies
!pip install -e .[metrics]
# Install bitsandbytes for optimized memory management
!pip install bitsandbytes

"""## Dataset creation e YAML Config"""

import json

# 1. Properly register the multi-factor dataset inside LLaMA-Factory directory structure
dataset_info = {
  "financial_dpo_multi_factor": {
    "file_name": "large_scale_financial_dpo_(multi_factor).json",
    "ranking": True,
    "columns": {
      "prompt": "instruction",
      "query": "input",
      "chosen": "chosen",
      "rejected": "rejected"
    }
  }
}

with open("data/dataset_info.json", "w", encoding="utf-8") as f:
    json.dump(dataset_info, f, indent=2, ensure_ascii=False)

# 2. Generate the fully commented English training specification file
yaml_content = """
### model
model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct

### method
stage: dpo
do_train: true
finetuning_type: lora
lora_target: all
pref_beta: 0.1
pref_loss: sigmoid

### dataset
dataset: financial_dpo_multi_factor
template: llama3
cutoff_len: 1024
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/llama3-8b/lora/dpo_financial
logging_steps: 10
save_steps: 100
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 5.0e-6
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 18000000
"""

with open("dpo_config.yaml", "w", encoding="utf-8") as f:
    f.write(yaml_content.strip())

print("Arquivo YAML atualizado com o nome correto do modelo!")

#*****************************************

from huggingface_hub import notebook_login

notebook_login()

"""## Model Qwen2.5-7B"""

yaml_content = """
### model
model_name_or_path: Qwen/Qwen2.5-7B-Instruct

### method
stage: dpo
do_train: true
finetuning_type: lora
lora_target: all
pref_beta: 0.1
pref_loss: sigmoid

### dataset
dataset: financial_dpo_multi_factor
template: qwen
cutoff_len: 1024
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/qwen-7b/lora/dpo_financial
logging_steps: 10
save_steps: 100
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 5.0e-6
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 18000000
"""

with open("qwen2_5dpo_config.yaml", "w", encoding="utf-8") as f:
    f.write(yaml_content.strip())

print("Arquivo YAML atualizado para usar o Qwen 2.5 (Livre de bloqueios)!")

!llamafactory-cli train qwen2_5dpo_config.yaml

"""## Model Meta-Llama-3-8B"""

yaml_content = """
### model
model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct  # Path to Meta's Llama 3 8B Instruct base model

### method
stage: dpo  # Specifies the training stage as Direct Preference Optimization
do_train: true  # Enables the training phase execution
finetuning_type: lora  # Uses Low-Rank Adaptation (LoRA) for parameter-efficient fine-tuning
lora_target: all  # Applies LoRA weights to all available linear layers to maximize capacity
pref_beta: 0.1  # KL divergence penalty coefficient; controls alignment strictness
pref_loss: sigmoid  # Loss function type used for evaluating preference ranking alignment

### dataset
dataset: financial_dpo_multi_factor  # Target multi-factor financial dataset registered in dataset_info.json
template: llama3  # Prompt template styling specifically matching Llama 3 tokenization requirements
cutoff_len: 1024  # Maximum sequence length (tokens) allowed before truncation
max_samples: 1000  # Upper limit of training samples to load from the JSON file
overwrite_cache: true  # Forces rewriting the preprocessed tokenization cache to avoid stale data
preprocessing_num_workers: 16  # Multi-processing CPU workers utilized during initial data tokenization

### output
output_dir: saves/llama3-8b/lora/dpo_financial  # Destination directory path for final weights and checkpoints (completely isolated)
logging_steps: 10  # Frequency of training steps before telemetry metrics are written
save_steps: 100  # Interval of training steps before saving a model checkpoint state
plot_loss: true  # Automatically plots and saves the loss curve diagram in the output directory
overwrite_output_dir: true  # Overwrites pre-existing target folders to clear previous run remnants

### train
per_device_train_batch_size: 2  # Training batch allocation per active GPU node
gradient_accumulation_steps: 8  # Steps over which gradients accumulate before an optimizer update (Effective Batch Size = 16)
learning_rate: 5.0e-6  # Peak learning rate for the AdamW optimization function
num_train_epochs: 3.0  # Number of complete tracking cycles through the entire dataset
lr_scheduler_type: cosine  # Decay curve style controlling the optimization pace over time
warmup_ratio: 0.1  # Fraction of the overall execution spent ramping up the learning rate
bf16: true  # Employs Brain Floating Point 16-bit precision for high-performance tensor acceleration
ddp_timeout: 18000000  # Extended multi-node sync timeout duration for Distributed Data Parallel arrays
"""

with open("llama3_dpo_config.yaml", "w", encoding="utf-8") as f:
    f.write(yaml_content.strip())

print("Arquivo 'llama3_dpo_config.yaml' criado com sucesso e isolado!")

!llamafactory-cli train llama3_dpo_config.yaml

"""## Modelo Gemma 2"""

yaml_content = """
### model
model_name_or_path: google/gemma-2-9b-it

### method
stage: dpo
do_train: true
finetuning_type: lora
lora_target: all
pref_beta: 0.1
pref_loss: sigmoid

### dataset
dataset: financial_dpo_multi_factor
template: gemma
cutoff_len: 1024
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/gemma2-9b/lora/dpo_financial
logging_steps: 10
save_steps: 100
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 5.0e-6
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 18000000
"""

with open("gemma2_dpo_config.yaml", "w", encoding="utf-8") as f:
    f.write(yaml_content.strip())

print("Configuração do Gemma 2 criada!")

!llamafactory-cli train gemma2_dpo_config.yaml

"""## Modelo DeepSeek-R1-Distill-Qwen-7B"""

yaml_content = """
### model
model_name_or_path: deepseek-ai/DeepSeek-R1-Distill-Qwen-7B

### method
stage: dpo
do_train: true
finetuning_type: lora
lora_target: all
pref_beta: 0.1
pref_loss: sigmoid

### dataset
dataset: financial_dpo_multi_factor
template: qwen  # Os modelos destilados do Qwen utilizam o template nativo do Qwen
cutoff_len: 1024
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/deepseek-r1-7b/lora/dpo_financial  # Pasta totalmente isolada
logging_steps: 10
save_steps: 100
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 5.0e-6
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 18000000
"""

with open("deepseek_dpo_config.yaml", "w", encoding="utf-8") as f:
    f.write(yaml_content.strip())

print("Configuração do DeepSeek-R1-Distill-Qwen-7B criada com sucesso!")

!llamafactory-cli train deepseek_dpo_config.yaml

"""# Chat Models"""

yaml_content = """
model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct
adapter_name_or_path: saves/llama3-8b/lora/dpo_financial
template: llama3
finetuning_type: lora
"""

with open("llama3_infer.yaml", "w", encoding="utf-8") as f:
    f.write(yaml_content.strip())

print("Arquivo de inferência do Llama 3 criado!")

!llamafactory-cli chat llama3_infer.yaml

"""## Download Weights"""

# Compacta toda a estrutura de salvamento dos 3 modelos em um único arquivo zip
!zip -r dpo_financial_experts.zip /content/LLaMA-Factory/saves/

from google.colab import files

files.download('dpo_financial_experts.zip')